// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkshopZagreb.Data;

#nullable disable

namespace WorkshopZagreb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604131936_AddIsArchived")]
    partial class AddIsArchived
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WorkshopZagreb.Models.ReservedDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReservedDays");
                });

            modelBuilder.Entity("WorkshopZagreb.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnsubscribedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("WorkshopZagreb.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntrioUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostInstagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostWebsite")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstagramPostUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BannerUrl = "/images/unutra.webp",
                            CreatedAt = new DateTime(2026, 6, 4, 13, 19, 36, 451, DateTimeKind.Utc).AddTicks(7781),
                            Date = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Naučite osnove akvarela u opuštenom okruženju uz kavu. Sve materijale osiguravamo mi!",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            EntrioUrl = "https://entrio.hr",
                            HostInstagram = "https://instagram.com/anakovac.art",
                            HostName = "Ana Kovač",
                            InstagramPostUrl = "https://www.instagram.com/workshop.zagreb/",
                            IsArchived = false,
                            MaxParticipants = 12,
                            Name = "Akvarel za početnike",
                            Price = 35m,
                            Slug = "akvarel-za-pocetnike",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            BannerUrl = "/images/table.webp",
                            CreatedAt = new DateTime(2026, 6, 4, 13, 19, 36, 451, DateTimeKind.Utc).AddTicks(7788),
                            Date = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Uvod u oblikovanje gline na lončarskom kolu. Iskustvo nije potrebno — samo volontiranje za pranje ruku.",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            HostName = "Marko Blažević",
                            InstagramPostUrl = "https://www.instagram.com/workshop.zagreb/",
                            IsArchived = false,
                            MaxParticipants = 8,
                            Name = "Keramika za sve",
                            Price = 45m,
                            Slug = "keramika-za-sve",
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            BannerUrl = "/images/prostor.jpg",
                            CreatedAt = new DateTime(2026, 6, 4, 13, 19, 36, 451, DateTimeKind.Utc).AddTicks(7792),
                            Date = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Naučite plesti makramé uzlove i izradite vlastiti zidni ukras.",
                            InstagramPostUrl = "https://www.instagram.com/workshop.zagreb/",
                            IsArchived = false,
                            MaxParticipants = 10,
                            Name = "Makramé osnove",
                            Price = 30m,
                            Slug = "makrame-osnove",
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("WorkshopZagreb.Models.WorkshopPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("WorkshopPhotos");
                });

            modelBuilder.Entity("WorkshopZagreb.Models.WorkshopPhoto", b =>
                {
                    b.HasOne("WorkshopZagreb.Models.Workshop", "Workshop")
                        .WithMany("Photos")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WorkshopZagreb.Models.Workshop", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
